name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x

      - run: npm ci

      - run: npm run build

      - run: npm run test

  install_latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          toolchain: latest

      - name: Run forc version
        run: forc --version
